import {
  AppointmentProps,
  MessageProps,
  NotificationProps,
  PatientProps,
} from "@/src/types";

export const notificationsData: NotificationProps[] = [
  {
    id: "1",
    title: "New Message from John Doe",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "message",
    date: "2025-02-06",
  },
  {
    id: "2",
    title: "New Message from Peter Parker",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "message",
    date: "2025-02-06",
  },
  {
    id: "3",
    title: "New Appointment with Sandy",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "appointment",
    date: "2025-02-06",
  },
  {
    id: "4",
    title: "New Message from Dr. Strange",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "message",
    date: "2025-02-05",
  },
  {
    id: "5",
    title: "New Appointment with Sandy",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "appointment",
    date: "2025-02-05",
  },
  {
    id: "6",
    title: "New Message from John Doe",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "message",
    date: "2025-03-06",
  },
  {
    id: "7",
    title: "New Message from Peter Parker",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "message",
    date: "2025-03-06",
  },
  {
    id: "8",
    title: "New Appointment with Sandy",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "appointment",
    date: "2025-03-06",
  },
  {
    id: "9",
    title: "New Message from Dr. Strange",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "message",
    date: "2025-03-06",
  },
  {
    id: "10",
    title: "New Appointment with Sandy",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    type: "appointment",
    date: "2025-03-06",
  },
];

// export const messagesData: MessageProps[] = [

//   {
//     id: "1",
//     name: "John Doe",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "3",
//   },
//   {
//     id: "2",
//     name: "Peter Parker",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-02-06",
//   },
//   {
//     id: "3",
//     name: "New Appointment with Sandy",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-02-06",
//   },
//   {
//     id: "4",
//     name: "Dr. Strange",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-02-06",
//   },
//   {
//     id: "5",
//     name: "John Doe",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-02-06",
//   },
//   {
//     id: "6",
//     name: "Peter Parker",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-03-06",
//   },
//   {
//     id: "7",
//     name: "John Doe",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-03-06",
//   },
//   {
//     id: "8",
//     name: "Peter Parker",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-03-06",
//   },
//   {
//     id: "9",
//     name: "New Appointment with Sandy",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-03-06",
//   },
//   {
//     id: "10",
//     name: "Dr. Strange",
//     message: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
//     image: require("@/assets/images/avatar.png"),
//     date: "2025-03-06",
//   },
// ];

export const patientsData: PatientProps[] = [
  {
    id: "1",
    name: "John Doe",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
  },
  {
    id: "2",
    name: "Peter Parker",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
  },
  {
    id: "3",
    name: "Sandy Williams",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
  },
  {
    id: "4",
    name: "Dr. Strange",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
  },
  {
    id: "5",
    name: "John Doe",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
  },
  {
    id: "6",
    name: "Peter Parker",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
  },
  {
    id: "7",
    name: "John Doe",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
  },
  {
    id: "8",
    name: "Peter Parker",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
  },
  {
    id: "9",
    name: "Sandy Williams",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
  },
  {
    id: "10",
    name: "Dr. Strange",
    number: "+2349012345678",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
  },
];

export const appointmentsData: AppointmentProps[] = [
  {
    id: "1",
    name: "John Doe",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
    time: "10:00 AM",
  },
  {
    id: "2",
    name: "Peter Parker",
    status: "offline",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
    time: "10:00 AM",
  },
  {
    id: "3",
    name: "Sandy Williams",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
    time: "10:00 AM",
  },
  {
    id: "4",
    name: "Dr. Strange",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
    time: "10:00 AM",
  },
  {
    id: "5",
    name: "John Doe",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-03-06",
    time: "10:00 AM",
  },
  {
    id: "6",
    name: "Peter Parker",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
    time: "10:00 AM",
  },
  {
    id: "7",
    name: "John Doe",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
    time: "10:00 AM",
  },
  {
    id: "8",
    name: "Peter Parker",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
    time: "10:00 AM",
  },
  {
    id: "9",
    name: "Sandy Williams",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
    time: "10:00 AM",
  },
  {
    id: "10",
    name: "Dr. Strange",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
    time: "10:00 AM",
  },
  {
    id: "11",
    name: "Sandy Williams",
    status: "offline",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
    time: "10:00 AM",
  },
  {
    id: "12",
    name: "Dr. Strange",
    status: "online",
    image: require("@/assets/images/avatar.png"),
    date: "2025-02-06",
    time: "10:00 AM",
  },
];
